"""Offline, versioned read-only research surface."""

from .contracts import (
    SURFACE_CONTRACT,
    SURFACE_SCHEMA_VERSION,
    ResearchSurfaceSnapshotV1,
    SurfaceAcceptanceStatus,
    SurfaceAnalysisView,
    SurfaceArtifactReference,
    SurfaceCDCMetric,
    SurfaceCoverageRecord,
    SurfaceGate,
    SurfaceGateRule,
    SurfaceGates,
    SurfaceHistoricalStatus,
    SurfaceMetrics,
    SurfaceNetCashMetric,
    SurfaceReadinessStatus,
    SurfaceSourceFreshness,
    SurfaceTargetScope,
    SurfaceThroughReturnMetric,
    SurfaceValidationStatus,
)
from .projection import (
    SurfaceProjectionError,
    build_research_surface_snapshot,
    build_surface_snapshot,
    load_research_surface_snapshot,
    project_research_surface,
    validate_research_surface_snapshot,
)

__all__ = [
    "SURFACE_CONTRACT",
    "SURFACE_SCHEMA_VERSION",
    "ResearchSurfaceSnapshotV1",
    "SurfaceAcceptanceStatus",
    "SurfaceAnalysisView",
    "SurfaceArtifactReference",
    "SurfaceCDCMetric",
    "SurfaceCoverageRecord",
    "SurfaceGate",
    "SurfaceGateRule",
    "SurfaceGates",
    "SurfaceHistoricalStatus",
    "SurfaceMetrics",
    "SurfaceNetCashMetric",
    "SurfaceProjectionError",
    "SurfaceReadinessStatus",
    "SurfaceSourceFreshness",
    "SurfaceTargetScope",
    "SurfaceThroughReturnMetric",
    "SurfaceValidationStatus",
    "build_research_surface_snapshot",
    "build_surface_snapshot",
    "load_research_surface_snapshot",
    "project_research_surface",
    "validate_research_surface_snapshot",
]
