"""Phase 6-D2B external notification delivery and delivery/receipt ledger.

Provider-neutral durable delivery over the validated terminal D2A/D1 alert
outbox.  The first and only transport is a generic HTTP webhook.  The
package imports no provider, research, model, analysis or pipeline code, and
never mutates Phase 6-A/6-C, D1 or D2A state.
"""

from .contracts import (
    ATTEMPT_CLASSIFICATIONS,
    MAX_WEBHOOK_PAYLOAD_BYTES,
    MONITORING_DELIVERY_DOMAIN,
    TELEGRAM_PAYLOAD_CONTRACT,
    TELEGRAM_TRANSPORT_ID,
    WEBHOOK_PAYLOAD_CONTRACT,
    WEBHOOK_TRANSPORT_ID,
    DeliveryFailureCode,
    DeliverySettingsV1,
    DeliveryStatus,
    MonitoringDeliveryAttemptV1,
    MonitoringDeliveryIntentV1,
    MonitoringDeliveryStateV1,
    MonitoringDispatchClaimV1,
    MonitoringTelegramPayloadV1,
    MonitoringWebhookAlertV1,
    MonitoringWebhookPayloadV1,
    delivery_identity,
)
from .locking import (
    DeliveryLockBusyError,
    DeliveryLockError,
    delivery_single_flight,
)
from .service import (
    AuthResolver,
    DeliveryClock,
    DeliveryDisabledError,
    DeliveryEndpointUnresolvedError,
    DeliveryLedgerConflictError,
    DeliveryNetworkDeniedError,
    DeliveryPayloadError,
    DeliveryRunOutcome,
    DeliverySourceError,
    EndpointResolver,
    MonitoringDeliveryService,
    backoff_seconds,
    build_delivery_payload,
    build_webhook_payload,
    delivery_status_projection,
    derive_delivery_state,
    published_state_is_behind,
    validate_dispatch_evidence,
)
from .store import (
    DeliveryLedgerError,
    DeliveryLedgerStore,
    DeliveryWriteKind,
    FailureInjector,
)
from .telegram import (
    TelegramBotTransport,
    classify_telegram_response,
    discover_telegram_chats,
    render_telegram_text,
    telegram_destination_id,
    telegram_endpoint_from_token,
)
from .transport import (
    ConnectionFactory,
    MonotonicClock,
    TransportOutcome,
    WebhookEndpointError,
    WebhookHttpTransport,
    WebhookRequest,
    WebhookTransport,
    WebhookTransportError,
)

__all__ = [
    "ATTEMPT_CLASSIFICATIONS",
    "AuthResolver",
    "ConnectionFactory",
    "DeliveryClock",
    "DeliveryDisabledError",
    "DeliveryEndpointUnresolvedError",
    "DeliveryFailureCode",
    "DeliveryLedgerConflictError",
    "DeliveryLedgerError",
    "DeliveryLedgerStore",
    "DeliveryLockBusyError",
    "DeliveryLockError",
    "DeliveryNetworkDeniedError",
    "DeliveryPayloadError",
    "DeliveryRunOutcome",
    "DeliverySettingsV1",
    "DeliverySourceError",
    "DeliveryStatus",
    "DeliveryWriteKind",
    "EndpointResolver",
    "FailureInjector",
    "MAX_WEBHOOK_PAYLOAD_BYTES",
    "MONITORING_DELIVERY_DOMAIN",
    "TELEGRAM_PAYLOAD_CONTRACT",
    "TELEGRAM_TRANSPORT_ID",
    "MonotonicClock",
    "MonitoringDeliveryAttemptV1",
    "MonitoringDeliveryIntentV1",
    "MonitoringDeliveryService",
    "MonitoringDeliveryStateV1",
    "MonitoringDispatchClaimV1",
    "MonitoringTelegramPayloadV1",
    "MonitoringWebhookAlertV1",
    "MonitoringWebhookPayloadV1",
    "TransportOutcome",
    "WEBHOOK_PAYLOAD_CONTRACT",
    "WEBHOOK_TRANSPORT_ID",
    "WebhookEndpointError",
    "WebhookHttpTransport",
    "WebhookRequest",
    "WebhookTransport",
    "WebhookTransportError",
    "TelegramBotTransport",
    "backoff_seconds",
    "build_delivery_payload",
    "build_webhook_payload",
    "delivery_identity",
    "delivery_single_flight",
    "delivery_status_projection",
    "classify_telegram_response",
    "discover_telegram_chats",
    "derive_delivery_state",
    "published_state_is_behind",
    "render_telegram_text",
    "telegram_destination_id",
    "telegram_endpoint_from_token",
    "validate_dispatch_evidence",
]
