"""Public model-neutral research and reporting boundaries."""

from .clients import (
    AnalystClient,
    AnalystClientError,
    AnalystResponse,
    CallableAnalystClient,
    ScriptedAnalystClient,
    coerce_analyst_response,
)
from .contracts import (
    RESEARCH_CONTRACT_VERSION,
    RESEARCH_PROMPT_VERSION,
    RESEARCH_PROTOCOL_VERSION,
    AgentRunMetadata,
    AnalystExecutionMode,
    AnalystRole,
    AnalystRun,
    AnalystRunStatus,
    BusinessQualityDimensionName,
    BusinessQualityResearchResult,
    CounterEvidenceClaim,
    DeterministicMetric,
    DimensionResearchResult,
    EvidenceClaim,
    EvidencePacket,
    PacketFact,
    ResearchFinding,
    ResearchIntent,
    ResearchQuestion,
    ResearchSession,
    ResearchTask,
    packet_fact_from_fact,
)
from .orchestration import (
    ResearchOrchestrator,
    ResearchValidationError,
    build_research_question,
    research_business_quality,
    run_business_quality_dimension,
    run_business_quality_research,
    run_research,
    validate_analyst_run,
)
from .packet import EvidencePacketBuilder, EvidencePacketError, build_evidence_packet
from .report import (
    ReportComposer,
    ReportSection,
    ResearchReport,
    ResearchWorkflowResult,
    compose_report,
)
from .workspace import ResearchArtifactStore, ResearchWorkspace, ResearchWorkspaceError

__all__ = [
    "AnalystClient",
    "AnalystClientError",
    "AnalystExecutionMode",
    "AnalystResponse",
    "AnalystRole",
    "AnalystRun",
    "AnalystRunStatus",
    "AgentRunMetadata",
    "BusinessQualityDimensionName",
    "BusinessQualityResearchResult",
    "CallableAnalystClient",
    "CounterEvidenceClaim",
    "DeterministicMetric",
    "DimensionResearchResult",
    "EvidenceClaim",
    "EvidencePacket",
    "EvidencePacketBuilder",
    "EvidencePacketError",
    "PacketFact",
    "ReportComposer",
    "ReportSection",
    "ResearchArtifactStore",
    "ResearchFinding",
    "ResearchIntent",
    "ResearchOrchestrator",
    "ResearchQuestion",
    "ResearchReport",
    "ResearchSession",
    "ResearchTask",
    "ResearchValidationError",
    "ResearchWorkflowResult",
    "ResearchWorkspace",
    "ResearchWorkspaceError",
    "RESEARCH_CONTRACT_VERSION",
    "RESEARCH_PROMPT_VERSION",
    "RESEARCH_PROTOCOL_VERSION",
    "ScriptedAnalystClient",
    "build_evidence_packet",
    "build_research_question",
    "coerce_analyst_response",
    "compose_report",
    "packet_fact_from_fact",
    "research_business_quality",
    "run_business_quality_dimension",
    "run_business_quality_research",
    "run_research",
    "validate_analyst_run",
]
