"""Bounded Quality Analyst / Skeptic / Adjudicator orchestration."""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence

from pydantic import ValidationError

from turtle_value_engine.adjustments import AdjustmentProposalWorkflow, adjustment_id_for
from turtle_value_engine.calculations import (
    BUSINESS_QUALITY_DIMENSIONS,
    calculate_business_quality_from_normalized_input,
)
from turtle_value_engine.config import RuleProfile, load_profile
from turtle_value_engine.effective_input import EFFECTIVE_ADJUSTMENT_FIELDS
from turtle_value_engine.models import (
    Adjustment,
    BusinessQualityDimension,
    CompanyAnalysis,
    NormalizedCompanyInput,
)
from turtle_value_engine.models.common import ProposedBy
from turtle_value_engine.providers.errors import AdjustmentWorkflowError
from turtle_value_engine.providers.normalization import deterministic_id

from .clients import AnalystClient, AnalystClientError, coerce_analyst_response
from .contracts import (
    RESEARCH_PROMPT_VERSION,
    RESEARCH_PROTOCOL_VERSION,
    AnalystRole,
    AnalystRun,
    BusinessQualityResearchResult,
    DimensionResearchResult,
    ResearchFinding,
    ResearchIntent,
    ResearchQuestion,
    ResearchSession,
    ResearchTask,
)
from .packet import EvidencePacketBuilder
from .report import ResearchWorkflowResult, compose_report
from .workspace import ResearchWorkspace


class ResearchValidationError(ValueError):
    """Raised when an untrusted analyst proposal cannot be accepted."""


_QUESTION_TEXTS: dict[str, str] = {
    "demand_durability": (
        "Why should customers still need this product or service five to ten years from now?"
    ),
    "cyclicality": (
        "How much of profit is generated by the business itself versus external cycle conditions?"
    ),
    "pricing_power": (
        "Can the company raise price or pass through cost inflation without losing "
        "material volume or share?"
    ),
    "moat": (
        "If a well-funded competitor entered today, why could it not easily replicate "
        "the economics?"
    ),
    "capital_efficiency": (
        "How much capital must continuously be fed back into the business to maintain "
        "or grow cash earnings?"
    ),
    "dependency": (
        "Could a concentrated customer, channel or supplier relationship impair the economics?"
    ),
    "regulatory_risk": (
        "Is regulation primarily a barrier that protects economics, or a policy lever "
        "that can destroy them?"
    ),
    "predictability": (
        "Without forecasting macro variables or stock prices, can we understand how "
        "this company will probably make money five years from now?"
    ),
}

_FOCUS_AREAS: dict[str, tuple[str, ...]] = {
    "demand_durability": (
        "recurring or repeat demand",
        "substitution and deferral risk",
        "revenue persistence and recession resilience",
    ),
    "cyclicality": (
        "profit and margin history across a cycle",
        "loss frequency and cash-flow volatility",
        "peak or trough conditions",
    ),
    "pricing_power": (
        "price and volume changes",
        "market-share response",
        "margin resilience during input-cost shocks",
    ),
    "moat": (
        "specific moat mechanism",
        "economic outcomes such as share, retention, ROIC or unit cost",
        "replication risk",
    ),
    "capital_efficiency": (
        "gross capex and working-capital intensity",
        "incremental returns on capital",
        "maintenance versus growth investment",
    ),
    "dependency": (
        "largest and top-five customers",
        "channel/platform concentration",
        "critical suppliers and replacement time",
    ),
    "regulatory_risk": (
        "barrier benefit versus policy damage risk",
        "licenses and government dependence",
        "geopolitical and external-input exposure",
    ),
    "predictability": (
        "key earnings drivers",
        "segment and accounting complexity",
        "M&A, fair-value and derivative dependence",
    ),
}


def build_research_question(
    dimension: str,
    intent: ResearchIntent,
) -> ResearchQuestion:
    """Build one versioned question from the fixed specification dimensions."""

    if dimension not in BUSINESS_QUALITY_DIMENSIONS:
        raise ResearchValidationError(f"unknown business-quality dimension: {dimension}")
    base = _QUESTION_TEXTS[dimension]
    if intent is ResearchIntent.THESIS:
        text = base
    elif intent is ResearchIntent.FALSIFICATION:
        text = f"What evidence would falsify this durability thesis? {base}"
    else:
        text = f"Adjudicate the supplied supporting and counter-evidence for this question: {base}"
    question_id = deterministic_id("research-question", dimension, intent.value, text)
    return ResearchQuestion(
        id=question_id,
        dimension=dimension,
        intent=intent,
        text=text,
        focus_areas=list(_FOCUS_AREAS[dimension]),
    )


def _unique(values: Iterable[str]) -> list[str]:
    return list(dict.fromkeys(values))


def _finding_evidence_ids(finding: ResearchFinding) -> list[str]:
    return finding.evidence_ids


def _normalize_proposal(
    adjustment: Adjustment,
    *,
    normalized_input: NormalizedCompanyInput,
    packet_evidence: Mapping[str, object],
) -> Adjustment:
    """Keep agent adjustments in the existing PROPOSED contract."""

    if adjustment.status.value != "PROPOSED":
        raise ResearchValidationError("analyst-originated adjustments must remain PROPOSED")
    if adjustment.proposed_by.value != "LLM" or adjustment.approved_by is not None:
        raise ResearchValidationError("LLM adjustments cannot carry approval")
    if adjustment.target_field not in EFFECTIVE_ADJUSTMENT_FIELDS:
        raise ResearchValidationError(
            f"unsupported adjustment target field: {adjustment.target_field}"
        )
    missing = sorted(set(adjustment.source_evidence_ids) - set(packet_evidence))
    if missing:
        raise ResearchValidationError(
            "adjustment cites evidence outside its packet: " + ", ".join(missing)
        )
    if not any(
        getattr(packet_evidence[evidence_id], "provenance", None) is not None
        for evidence_id in adjustment.source_evidence_ids
    ):
        raise ResearchValidationError(
            f"adjustment {adjustment.id!r} is not backed by persisted filing provenance"
        )
    try:
        expected_id = adjustment_id_for(adjustment, normalized_input=normalized_input)
    except (TypeError, ValueError, ValidationError) as exc:
        raise ResearchValidationError(
            f"cannot derive deterministic adjustment identity: {exc}"
        ) from exc
    if adjustment.id == expected_id:
        return adjustment
    return adjustment.model_copy(update={"id": expected_id})


def _normalize_finding(
    finding: ResearchFinding,
    *,
    task: ResearchTask,
    normalized_input: NormalizedCompanyInput,
) -> ResearchFinding:
    """Validate all proposal references before the run is persisted."""

    if (
        finding.analysis_id != task.analysis_id
        or finding.listing_id != task.listing_id
        or finding.as_of != task.as_of
        or finding.role is not task.role
        or finding.question_id != task.question.id
        or finding.dimension != task.question.dimension
    ):
        raise ResearchValidationError("analyst finding does not match its research task")
    if (
        len(finding.supporting_claims) + len(finding.counter_evidence_claims)
        > task.max_output_claims
    ):
        raise ResearchValidationError("analyst finding exceeds the task claim limit")
    if len(finding.unresolved_questions) > task.max_unresolved_questions:
        raise ResearchValidationError("analyst finding exceeds the unresolved-question limit")
    available_evidence = task.packet.evidence_by_id
    evidence_ids = _finding_evidence_ids(finding)
    missing_evidence = sorted(set(evidence_ids) - set(available_evidence))
    if missing_evidence:
        raise ResearchValidationError(
            "analyst finding cites evidence outside its packet: " + ", ".join(missing_evidence)
        )
    metric_ids = set(task.packet.metric_ids)
    missing_metrics = sorted(set(finding.deterministic_metric_ids) - metric_ids)
    missing_metrics.extend(
        metric_id
        for claim in (*finding.supporting_claims, *finding.counter_evidence_claims)
        for metric_id in claim.deterministic_metric_ids
        if metric_id not in metric_ids
    )
    if missing_metrics:
        raise ResearchValidationError(
            "analyst finding cites deterministic metrics outside its packet: "
            + ", ".join(_unique(missing_metrics))
        )
    proposals = [
        _normalize_proposal(
            adjustment,
            normalized_input=normalized_input,
            packet_evidence=available_evidence,
        )
        for adjustment in finding.proposed_adjustments
    ]
    return finding.model_copy(update={"proposed_adjustments": proposals})


def validate_analyst_run(
    task: ResearchTask,
    run: AnalystRun,
    normalized_input: NormalizedCompanyInput,
) -> AnalystRun:
    """Public fail-closed validator for model output against a persisted task."""

    try:
        run.validate_against_task(task)
        finding = _normalize_finding(
            run.finding,
            task=task,
            normalized_input=normalized_input,
        )
        validated = AnalystRun.build(task, finding, run.metadata)
        validated.validate_against_task(task)
        return validated
    except (TypeError, ValueError, ValidationError) as exc:
        if isinstance(exc, ResearchValidationError):
            raise
        raise ResearchValidationError(f"invalid analyst run {run.run_id}: {exc}") from exc


def _call_analyst(
    client: AnalystClient,
    task: ResearchTask,
    normalized_input: NormalizedCompanyInput,
) -> AnalystRun:
    if not hasattr(client, "analyze") or not callable(client.analyze):
        raise ResearchValidationError("analyst client must implement analyze(task)")
    try:
        response = client.analyze(task)
        run = coerce_analyst_response(task, response)
        return validate_analyst_run(task, run, normalized_input)
    except AnalystClientError as exc:
        raise ResearchValidationError(str(exc)) from exc
    except Exception as exc:
        raise ResearchValidationError(
            f"analyst client failed for task {task.task_id}: {exc}"
        ) from exc


def _dimension_from_finding(finding: ResearchFinding) -> BusinessQualityDimension:
    if finding.dimension is None or finding.proposed_score is None:
        raise ResearchValidationError(
            "adjudicator must return a proposed score for every business-quality dimension"
        )
    if not finding.counter_evidence_claims and not finding.counter_evidence_checked:
        raise ResearchValidationError(
            "adjudicator must provide counter-evidence or explicitly record the checks performed"
        )
    support_ids = _unique(
        evidence_id for claim in finding.supporting_claims for evidence_id in claim.evidence_ids
    )
    counter_ids = _unique(
        evidence_id
        for claim in finding.counter_evidence_claims
        for evidence_id in claim.evidence_ids
    )
    reasoning = finding.summary
    if not counter_ids and finding.counter_evidence_checked:
        reasoning += " Counter-evidence checked; no material counter-evidence found."
    return BusinessQualityDimension(
        dimension=finding.dimension,
        score=finding.proposed_score,
        supporting_evidence_ids=support_ids,
        counter_evidence_ids=counter_ids,
        confidence=finding.confidence,
        reasoning_summary=reasoning,
    )


def _persist_proposed_adjustments(
    findings: Iterable[ResearchFinding],
    *,
    normalized_input: NormalizedCompanyInput,
    workspace: ResearchWorkspace | None,
) -> list[Adjustment]:
    """Persist proposals through the Phase 3 lifecycle when a workspace exists."""

    proposals: dict[str, Adjustment] = {}
    workflow = AdjustmentProposalWorkflow(workspace.root) if workspace is not None else None
    for finding in findings:
        for adjustment in finding.proposed_adjustments:
            if workflow is not None:
                try:
                    # Keep the analyst output PROPOSED even when an earlier
                    # run has already been reviewed.  ``append`` is used for
                    # the durable lifecycle record; its accepted/rejected
                    # replay value must not rewrite this run's proposal.
                    workflow.append(
                        adjustment,
                        proposer=ProposedBy.LLM,
                        normalized_input=normalized_input,
                        evidence_index=normalized_input.evidence_index,
                    )
                except (AdjustmentWorkflowError, TypeError, ValueError) as exc:
                    raise ResearchValidationError(
                        f"cannot persist analyst adjustment {adjustment.id}: {exc}"
                    ) from exc
            previous = proposals.get(adjustment.id)
            if previous is not None and previous.model_dump(mode="json") != adjustment.model_dump(
                mode="json"
            ):
                raise ResearchValidationError(
                    f"conflicting analyst adjustment content for ID {adjustment.id}"
                )
            proposals[adjustment.id] = adjustment
    return [proposals[key] for key in sorted(proposals)]


def run_business_quality_dimension(
    normalized_input: NormalizedCompanyInput,
    dimension: str,
    quality_analyst: AnalystClient,
    skeptic: AnalystClient,
    adjudicator: AnalystClient,
    *,
    profile: RuleProfile | None = None,
    deterministic_analysis: CompanyAnalysis | None = None,
    packet_builder: EvidencePacketBuilder | None = None,
    workspace: ResearchWorkspace | None = None,
    prompt_version: str = RESEARCH_PROMPT_VERSION,
    protocol_version: str = RESEARCH_PROTOCOL_VERSION,
) -> DimensionResearchResult:
    """Run and validate one B01–B08 Quality/Skeptic/Adjudicator slice."""

    if not isinstance(normalized_input, NormalizedCompanyInput):
        raise TypeError("normalized_input must be a NormalizedCompanyInput")
    if dimension not in BUSINESS_QUALITY_DIMENSIONS:
        raise ResearchValidationError(f"unknown business-quality dimension: {dimension}")
    if profile is not None and profile.profile.id != normalized_input.profile_id:
        raise ResearchValidationError(
            "normalized input profile_id does not match the supplied rule profile"
        )
    builder = packet_builder or EvidencePacketBuilder(protocol_version=protocol_version)
    packets = []
    tasks = []
    runs = []

    def persist(packet, task, run) -> None:
        packets.append(packet)
        tasks.append(task)
        runs.append(run)
        if workspace is not None:
            workspace.save_packet(packet)
            workspace.save_task(task)
            workspace.save_run(run)

    def make_task(role: AnalystRole, question: ResearchQuestion, packet, **context):
        return ResearchTask.build(
            analysis_id=normalized_input.analysis_id,
            listing_id=normalized_input.company.primary_listing,
            as_of=normalized_input.as_of,
            profile_id=normalized_input.profile_id,
            role=role,
            question=question,
            packet=packet,
            prompt_version=prompt_version,
            protocol_version=protocol_version,
            **context,
        )

    quality_question = build_research_question(dimension, ResearchIntent.THESIS)
    quality_packet = builder.build(
        normalized_input,
        question=quality_question,
        role=AnalystRole.QUALITY_ANALYST,
        analysis=deterministic_analysis,
    )
    quality_task = make_task(AnalystRole.QUALITY_ANALYST, quality_question, quality_packet)
    quality_run = _call_analyst(quality_analyst, quality_task, normalized_input)
    persist(quality_packet, quality_task, quality_run)

    skeptic_question = build_research_question(dimension, ResearchIntent.FALSIFICATION)
    skeptic_packet = builder.build(
        normalized_input,
        question=skeptic_question,
        role=AnalystRole.SKEPTIC,
        analysis=deterministic_analysis,
        evidence_ids=quality_packet.available_evidence_ids,
    )
    skeptic_task = make_task(
        AnalystRole.SKEPTIC,
        skeptic_question,
        skeptic_packet,
        context_run_ids=[quality_run.run_id],
        context_findings=[quality_run.finding],
    )
    skeptic_run = _call_analyst(skeptic, skeptic_task, normalized_input)
    persist(skeptic_packet, skeptic_task, skeptic_run)

    adjudicator_question = build_research_question(dimension, ResearchIntent.ADJUDICATION)
    adjudicator_packet = builder.build(
        normalized_input,
        question=adjudicator_question,
        role=AnalystRole.ADJUDICATOR,
        analysis=deterministic_analysis,
        evidence_ids=quality_packet.available_evidence_ids,
    )
    adjudicator_task = make_task(
        AnalystRole.ADJUDICATOR,
        adjudicator_question,
        adjudicator_packet,
        context_run_ids=[quality_run.run_id, skeptic_run.run_id],
        context_findings=[quality_run.finding, skeptic_run.finding],
    )
    adjudicator_run = _call_analyst(adjudicator, adjudicator_task, normalized_input)
    persist(adjudicator_packet, adjudicator_task, adjudicator_run)

    all_findings = [quality_run.finding, skeptic_run.finding, adjudicator_run.finding]
    proposals = _persist_proposed_adjustments(
        all_findings,
        normalized_input=normalized_input,
        workspace=workspace,
    )
    return DimensionResearchResult(
        analysis_id=normalized_input.analysis_id,
        listing_id=normalized_input.company.primary_listing,
        as_of=normalized_input.as_of,
        profile_id=normalized_input.profile_id,
        dimension=dimension,
        packets=packets,
        tasks=tasks,
        analyst_runs=runs,
        proposed_dimension=_dimension_from_finding(adjudicator_run.finding),
        proposed_adjustments=proposals,
    )


def run_business_quality_research(
    normalized_input: NormalizedCompanyInput,
    quality_analyst: AnalystClient,
    skeptic: AnalystClient,
    adjudicator: AnalystClient,
    *,
    profile: RuleProfile | None = None,
    deterministic_analysis: CompanyAnalysis | None = None,
    dimensions: Sequence[str] = BUSINESS_QUALITY_DIMENSIONS,
    packet_builder: EvidencePacketBuilder | None = None,
    workspace: ResearchWorkspace | None = None,
    prompt_version: str = RESEARCH_PROMPT_VERSION,
    protocol_version: str = RESEARCH_PROTOCOL_VERSION,
) -> BusinessQualityResearchResult:
    """Run the full eight-dimension adversarial workflow with frozen bounds."""

    if not isinstance(normalized_input, NormalizedCompanyInput):
        raise TypeError("normalized_input must be a NormalizedCompanyInput")
    active_profile = profile or load_profile(normalized_input.profile_id)
    if active_profile.profile.id != normalized_input.profile_id:
        raise ResearchValidationError(
            "normalized input profile_id does not match the supplied rule profile"
        )
    dimensions = tuple(dimensions)
    if dimensions != BUSINESS_QUALITY_DIMENSIONS:
        raise ResearchValidationError(
            "the standard Business Quality workflow requires all eight fixed dimensions"
        )
    builder = packet_builder or EvidencePacketBuilder(protocol_version=protocol_version)
    dimension_runs = []
    packets = []
    tasks = []
    runs = []
    for dimension in dimensions:
        dimension_run = run_business_quality_dimension(
            normalized_input,
            dimension,
            quality_analyst,
            skeptic,
            adjudicator,
            profile=active_profile,
            deterministic_analysis=deterministic_analysis,
            packet_builder=builder,
            workspace=workspace,
            prompt_version=prompt_version,
            protocol_version=protocol_version,
        )
        dimension_runs.append(dimension_run)
        packets.extend(dimension_run.packets)
        tasks.extend(dimension_run.tasks)
        runs.extend(dimension_run.analyst_runs)

    dimension_results = [item.proposed_dimension for item in dimension_runs]
    business_quality = calculate_business_quality_from_normalized_input(
        normalized_input,
        dimension_results,
        active_profile,
    )
    unique_adjustments: dict[str, Adjustment] = {}
    for item in dimension_runs:
        for adjustment in item.proposed_adjustments:
            previous = unique_adjustments.get(adjustment.id)
            if previous is not None and previous.model_dump(mode="json") != adjustment.model_dump(
                mode="json"
            ):
                raise ResearchValidationError(
                    f"conflicting analyst adjustment content for ID {adjustment.id}"
                )
            unique_adjustments[adjustment.id] = adjustment
    session = ResearchSession.build(
        analysis_id=normalized_input.analysis_id,
        listing_id=normalized_input.company.primary_listing,
        as_of=normalized_input.as_of,
        profile_id=normalized_input.profile_id,
        packet_ids=[packet.packet_id for packet in packets],
        task_ids=[task.task_id for task in tasks],
        analyst_run_ids=[run.run_id for run in runs],
        proposed_adjustment_ids=sorted(unique_adjustments),
        accepted_adjustment_ids=[],
        business_quality_available=True,
        protocol_version=protocol_version,
    )
    result = BusinessQualityResearchResult(
        analysis_id=normalized_input.analysis_id,
        listing_id=normalized_input.company.primary_listing,
        as_of=normalized_input.as_of,
        profile_id=normalized_input.profile_id,
        dimension_results=business_quality.dimension_results,
        dimension_runs=dimension_runs,
        business_quality=business_quality,
        packets=packets,
        tasks=tasks,
        analyst_runs=runs,
        proposed_adjustments=[unique_adjustments[key] for key in sorted(unique_adjustments)],
        session_id=session.session_id,
    )
    if workspace is not None:
        workspace.save_business_quality(result)
        workspace.save_session(session)
    return result


def research_business_quality(*args, **kwargs) -> BusinessQualityResearchResult:
    """Compatibility alias with a noun-first public API."""

    return run_business_quality_research(*args, **kwargs)


class ResearchOrchestrator:
    """Composable prepare-independent research → analyze → report facade.

    Preparation is intentionally injected as an already validated
    ``NormalizedCompanyInput``.  Callers may obtain it from ``tve prepare`` or
    any provider/cache implementation; this class performs no hidden network
    work.  The only model calls are the three injected analyst clients.
    """

    def __init__(
        self,
        quality_analyst: AnalystClient,
        skeptic: AnalystClient,
        adjudicator: AnalystClient,
        *,
        profile: RuleProfile | None = None,
        packet_builder: EvidencePacketBuilder | None = None,
        workspace: ResearchWorkspace | None = None,
    ) -> None:
        self.quality_analyst = quality_analyst
        self.skeptic = skeptic
        self.adjudicator = adjudicator
        self.profile = profile
        self.packet_builder = packet_builder
        self.workspace = workspace

    def research_business_quality(
        self,
        normalized_input: NormalizedCompanyInput,
        *,
        deterministic_analysis: CompanyAnalysis | None = None,
    ) -> BusinessQualityResearchResult:
        return run_business_quality_research(
            normalized_input,
            self.quality_analyst,
            self.skeptic,
            self.adjudicator,
            profile=self.profile,
            deterministic_analysis=deterministic_analysis,
            packet_builder=self.packet_builder,
            workspace=self.workspace,
        )

    def research(
        self,
        normalized_input: NormalizedCompanyInput,
        *,
        accepted_adjustments: Sequence[Adjustment] | None = None,
    ):
        """Run deterministic baseline, adversarial BQ research, final analysis and report."""

        from turtle_value_engine.pipeline import (
            run_analyze,
            run_analyze_with_accepted_adjustments,
        )
        from turtle_value_engine.traceability import build_decision_trace

        active_profile = self.profile or load_profile(normalized_input.profile_id)
        baseline = run_analyze(normalized_input, active_profile)
        business_quality_result = self.research_business_quality(
            normalized_input,
            deterministic_analysis=baseline,
        )
        final_analysis = (
            run_analyze_with_accepted_adjustments(
                normalized_input,
                accepted_adjustments,
                active_profile,
                business_quality=business_quality_result.business_quality,
            )
            if accepted_adjustments
            else run_analyze(
                normalized_input,
                active_profile,
                business_quality=business_quality_result.business_quality,
            )
        )
        trace = build_decision_trace(final_analysis)
        accepted_ids = sorted(
            adjustment.id
            for adjustment in final_analysis.adjustments
            if adjustment.status.value == "ACCEPTED"
        )
        analysis_artifact_id = None
        trace_artifact_id = None
        if self.workspace is not None:
            analysis_artifact_id = self.workspace.save_analysis(final_analysis).stem
            trace_artifact_id = self.workspace.save_trace(trace).stem
        session = ResearchSession.build(
            analysis_id=normalized_input.analysis_id,
            listing_id=normalized_input.company.primary_listing,
            as_of=normalized_input.as_of,
            profile_id=normalized_input.profile_id,
            packet_ids=[packet.packet_id for packet in business_quality_result.packets],
            task_ids=[task.task_id for task in business_quality_result.tasks],
            analyst_run_ids=[run.run_id for run in business_quality_result.analyst_runs],
            proposed_adjustment_ids=[
                adjustment.id for adjustment in business_quality_result.proposed_adjustments
            ],
            accepted_adjustment_ids=accepted_ids,
            business_quality_available=True,
            business_quality_artifact_id=business_quality_result.session_id,
            final_analysis_id=final_analysis.analysis_id,
            final_analysis_artifact_id=analysis_artifact_id,
            final_trace_artifact_id=trace_artifact_id,
        )
        report = compose_report(
            final_analysis,
            analyst_runs=business_quality_result.analyst_runs,
            research_session_id=session.session_id,
        )
        session = session.model_copy(update={"report_id": report.report_id})
        if self.workspace is not None:
            self.workspace.save_session(session)
            self.workspace.save_report(report)
        return ResearchWorkflowResult(
            session=session,
            business_quality_research=business_quality_result,
            analysis=final_analysis,
            decision_trace=trace,
            report=report,
        )

    def run(self, *args, **kwargs):
        """Alias for runtimes that call the top-level workflow ``run``."""

        return self.research(*args, **kwargs)


def run_research(
    normalized_input: NormalizedCompanyInput,
    quality_analyst: AnalystClient,
    skeptic: AnalystClient,
    adjudicator: AnalystClient,
    **kwargs,
):
    """Functional top-level entry point for external agent runtimes."""

    orchestrator = ResearchOrchestrator(
        quality_analyst,
        skeptic,
        adjudicator,
        profile=kwargs.pop("profile", None),
        packet_builder=kwargs.pop("packet_builder", None),
        workspace=kwargs.pop("workspace", None),
    )
    accepted_adjustments = kwargs.pop("accepted_adjustments", None)
    if kwargs:
        raise TypeError("unsupported run_research options: " + ", ".join(sorted(kwargs)))
    return orchestrator.research(
        normalized_input,
        accepted_adjustments=accepted_adjustments,
    )


__all__ = [
    "ResearchValidationError",
    "ResearchOrchestrator",
    "build_research_question",
    "run_business_quality_dimension",
    "research_business_quality",
    "run_research",
    "run_business_quality_research",
    "validate_analyst_run",
]
